const products = [
  {
    id: 93,
    title: "Brown Leather Belt Watch",
    description:
      "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    price: 89.99,
    discountPercentage: 15.01,
    rating: 4.47,
    stock: 69,
    tags: ["watches", "leather watches"],
    brand: "Fashion Timepieces",
    sku: "WGZ21MSA",
    weight: 10,
    dimensions: {
      width: 18.39,
      height: 10.82,
      depth: 10.52,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Eli Ward",
        reviewerEmail: "eli.ward@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Stella Hughes",
        reviewerEmail: "stella.hughes@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "9559180055872",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/thumbnail.png",
  },
  {
    id: 94,
    title: "Longines Master Collection",
    description:
      "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.",
    price: 1499.99,
    discountPercentage: 0.64,
    rating: 2.64,
    stock: 65,
    tags: ["watches", "luxury watches"],
    brand: "Longines",
    sku: "LA7B9XEV",
    weight: 2,
    dimensions: {
      width: 5.83,
      height: 12.48,
      depth: 7.65,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Victoria McDonald",
        reviewerEmail: "victoria.mcdonald@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Mia Rodriguez",
        reviewerEmail: "mia.rodriguez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "1865008250672",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png",
  },
  {
    id: 95,
    title: "Rolex Cellini Date Black Dial",
    description:
      "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.",
    price: 8999.99,
    discountPercentage: 14.28,
    rating: 3.61,
    stock: 84,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "J3GPKQW0",
    weight: 6,
    dimensions: {
      width: 12.17,
      height: 27.99,
      depth: 10.36,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Gavin Stanley",
        reviewerEmail: "gavin.stanley@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Stella Hughes",
        reviewerEmail: "stella.hughes@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "8917585155737",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/thumbnail.png",
  },
  {
    id: 96,
    title: "Rolex Cellini Moonphase",
    description:
      "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.",
    price: 12999.99,
    discountPercentage: 5.7,
    rating: 4.52,
    stock: 33,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "LUZDIKKR",
    weight: 5,
    dimensions: {
      width: 28.07,
      height: 13.43,
      depth: 10.81,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jacob Cooper",
        reviewerEmail: "jacob.cooper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Elijah Cruz",
        reviewerEmail: "elijah.cruz@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "0330714338454",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png",
  },
  {
    id: 97,
    title: "Rolex Datejust",
    description:
      "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.",
    price: 10999.99,
    discountPercentage: 9.69,
    rating: 4.94,
    stock: 11,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "86V20NWJ",
    weight: 5,
    dimensions: {
      width: 9.68,
      height: 7.29,
      depth: 5.67,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Max Russell",
        reviewerEmail: "max.russell@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jonathan Pierce",
        reviewerEmail: "jonathan.pierce@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Asher Scott",
        reviewerEmail: "asher.scott@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "4957618378388",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/thumbnail.png",
  },
  {
    id: 98,
    title: "Rolex Submariner Watch",
    description:
      "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.",
    price: 13999.99,
    discountPercentage: 0.82,
    rating: 2.97,
    stock: 35,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "XFGRO0O5",
    weight: 5,
    dimensions: {
      width: 5.22,
      height: 27.59,
      depth: 16.93,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Emily Brown",
        reviewerEmail: "emily.brown@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Julian James",
        reviewerEmail: "julian.james@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "6567997358364",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/thumbnail.png",
  },
];

export default products;
